### ISSUE TITLE
Use EncodeUri() if part of the URL path or EncodeUriComponent() if used as a URL parameter

### ISSUE THREAD

**Issue by semisight** [humanzai/gtm-pixel-template#1]
https://github.com/humanzai/gtm-pixel-template/blob/9be880418cca9a936a738a6bb00dcd1f7619c8d6/template.tpl#L70

When reviewing your template we've noticed that it is using parameters to build a url. It's a best practice to use [EncodeUri()](https://developers.google.com/tag-manager/templates/api#encodeuri) if part of the URL path or [EncodeUriComponent()](https://developers.google.com/tag-manager/templates/api#encodeuricomponent) if used as a URL parameter.

**Comment by humanzai** [comment]
@semisight Fixed and merged as a part of this commit [0683f20c2a2d9138155a73d165a45023b866ad00](https://github.com/humanzai/gtm-pixel-template/commit/0683f20c2a2d9138155a73d165a45023b866ad00)
